# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b79f4102c3d05737e2f81100fe5bf704d28c76ff0b6f3575eae8f3cdecaff41e63524d4f946de10e254bb61a5491437a1e98a2d84465c8463fa6fd34dd21f4a

test:
  secret_key_base: a82c61b221f80b3b33a11aa0d83686eed2d0f1826de51dad8aa65dc5353b40a3d85952b7999b9cce1469c01bb975efe1e7415bad54f55c3190daa5de8f754300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
